#include "PZEM.h"
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"
#include <stdint.h>
#include <string.h>

 

/* =========================================================================
 * PZEM-004T (v3.0) AC energy meter driver - Modbus RTU over SCI UART0
 *
 * Wiring (board side):
 *   P411 (TXD0) -> PZEM RX
 *   P204 (RXD0) <- PZEM TX
 *   3V3 GND     -- PZEM GND
 *   +5V         -> PZEM 5V (the TTL header is passive, 5V is mandatory)
 *
 * Frames:
 *   Read req  (8 B):  addr 0x04 reg_hi reg_lo cnt_hi cnt_lo crc_lo crc_hi
 *   Read resp (25B):  addr 0x04 0x14 [20 data bytes] crc_lo crc_hi
 *   Error resp (5B):  addr 0x84 err crc_lo crc_hi
 *
 * 32-bit registers (current, power, energy) are encoded by the PZEM as
 * [low16-hi, low16-lo, high16-hi, high16-lo]. See parse_meas() below.
 * ========================================================================= */
/* FSP handles generated by the configurator. */

extern sci_uart_instance_ctrl_t g_uart0_ctrl;

extern const uart_cfg_t         g_uart0_cfg;

 

/* ---- Protocol constants ------------------------------------------------- */
#define PZEM_FC_READ_HOLDING      (0x03U)
#define PZEM_FC_READ_INPUT        (0x04U)
#define PZEM_FC_WRITE_SINGLE      (0x06U)
#define PZEM_FC_RESET_ENERGY      (0x42U)
#define PZEM_ERR_MASK             (0x80U)
#define PZEM_REG_MEAS_BASE        (0x0000U)
#define PZEM_REG_MEAS_COUNT       (10U)
#define PZEM_REG_ALARM_THR        (0x0001U)
#define PZEM_REG_ADDRESS          (0x0002U)
#define PZEM_FRAME_MAX            (32U)
#define PZEM_RESP_MEAS_LEN        (3U + (PZEM_REG_MEAS_COUNT * 2U) + 2U) /* 25 */
#define PZEM_REQ_READ_LEN         (8U)
#define PZEM_REQ_WRITE_LEN        (8U)
#define PZEM_REQ_RESET_LEN        (4U)
/* ---- Timing ------------------------------------------------------------- */
#define PZEM_BAUDRATE             (9600U)
#define PZEM_TX_TIMEOUT_MS        (100U)
#define PZEM_FIRST_BYTE_MS        (250U)  /* normal poll                  */
#define PZEM_FIRST_BYTE_RESET_MS  (500U)
#define PZEM_INTER_BYTE_MS        (15U)   /* >>1 char @ 9600 (~1.04 ms)   */
#define PZEM_POLL_PERIOD_MS       (300U)
#define PZEM_INTER_FRAME_MS       (10U)   /* >3.5 char Modbus silence     */
/* ---- Sync primitives ---------------------------------------------------- */

static SemaphoreHandle_t g_bus_mutex;
static StaticSemaphore_t g_bus_mutex_buf;
static SemaphoreHandle_t g_tx_sem;

static StaticSemaphore_t g_tx_sem_buf;
static SemaphoreHandle_t g_rx_sem;       /* binary: "at least 1 new byte" */
static StaticSemaphore_t g_rx_sem_buf;

 

/* ---- RX accumulator (filled from ISR via UART_EVENT_RX_CHAR) ----------- */
static volatile uint8_t  g_rx_buf[PZEM_FRAME_MAX];
static volatile uint16_t g_rx_idx;
/* ---- Latest measurement mailbox (length-1 queue) ----------------------- */
static QueueHandle_t g_data_q;
static StaticQueue_t g_data_q_buf;
static uint8_t       g_data_q_storage[sizeof(pzem_data_t)];
static volatile bool g_uart_open = false;
static volatile uint32_t g_last_sample_ms = 0U;
/* =========================================================================
 * CRC-16 (Modbus): init 0xFFFF, poly 0xA001 reflected.
 * ========================================================================= */
static uint16_t pzem_crc16(const uint8_t * data, size_t len)
{
    uint16_t crc = 0xFFFFU;
    for (size_t i = 0U; i < len; i++)
    {
        crc ^= (uint16_t) data[i];
        for (uint8_t b = 0U; b < 8U; b++)
        {
            if (0U != (crc & 0x0001U))
            {
                crc = (uint16_t) ((crc >> 1) ^ 0xA001U);
            }
            else
            {
                crc >>= 1;
            }
        }
    }
    return crc;
}
/* =========================================================================
 * UART callback (runs in SCI ISR context).
 * ========================================================================= */

static void pzem_uart_cb(uart_callback_args_t * p_args)

{

    BaseType_t hp_woken = pdFALSE;
    switch (p_args->event)
    {
        case UART_EVENT_TX_COMPLETE:
            xSemaphoreGiveFromISR(g_tx_sem, &hp_woken);
            break;
        case UART_EVENT_RX_CHAR:
            if (g_rx_idx < PZEM_FRAME_MAX)
            {
                g_rx_buf[g_rx_idx++] = (uint8_t) p_args->data;
            }
            xSemaphoreGiveFromISR(g_rx_sem, &hp_woken);
            break;
        default:
            /* RX_ERR_*, BREAK, etc. - ignored; CRC will reject the frame. */
            break;
    }

    portYIELD_FROM_ISR(hp_woken);

}

/* =========================================================================
 * Low-level helpers.
 * ========================================================================= */
static void pzem_rx_reset(void)
{
    g_rx_idx = 0U;
    /* Drain any pending give on the binary RX semaphore. */
    (void) xSemaphoreTake(g_rx_sem, 0);
}

static bool pzem_uart_send(const uint8_t * buf, uint16_t len)
{
    (void) xSemaphoreTake(g_tx_sem, 0);
    if (FSP_SUCCESS != R_SCI_UART_Write(&g_uart0_ctrl, buf, len))
    {
        return false;
    }
    return pdTRUE == xSemaphoreTake(g_tx_sem,
                                    pdMS_TO_TICKS(PZEM_TX_TIMEOUT_MS));
}

/* Block up to first_ms for the first received byte, then keep accumulating
 * until inter_ms elapses with no new byte. Returns total bytes captured. */
static uint16_t pzem_uart_recv_frame(uint32_t first_ms, uint32_t inter_ms)
{
    if (pdTRUE != xSemaphoreTake(g_rx_sem, pdMS_TO_TICKS(first_ms)))
    {
        return 0U;
    }
    /* Modbus end-of-frame: silence > 3.5 char-times. Loop until quiet. */
    while (pdTRUE == xSemaphoreTake(g_rx_sem, pdMS_TO_TICKS(inter_ms)))
    {
        /* New byte(s) captured by the ISR; keep waiting. */
    }
    return g_rx_idx;
}

/* Build "read N registers" request (FC 0x03 or 0x04). */
static uint16_t pzem_build_read_req(uint8_t * buf,
                                    uint8_t   addr,
                                    uint8_t   fc,
                                    uint16_t  reg,
                                    uint16_t  count)
{
    buf[0] = addr;
    buf[1] = fc;
    buf[2] = (uint8_t) (reg >> 8);
    buf[3] = (uint8_t) (reg & 0xFFU);
    buf[4] = (uint8_t) (count >> 8);
    buf[5] = (uint8_t) (count & 0xFFU);

    uint16_t crc = pzem_crc16(buf, 6U);
    buf[6] = (uint8_t) (crc & 0xFFU);      /* CRC LO first (Modbus standard) */
    buf[7] = (uint8_t) (crc >> 8);
    return 8U;
}

/* Build "write single register" request (FC 0x06). */
static uint16_t pzem_build_write_req(uint8_t * buf,
                                     uint8_t   addr,
                                     uint16_t  reg,
                                     uint16_t  value)
{
    buf[0] = addr;
    buf[1] = PZEM_FC_WRITE_SINGLE;
    buf[2] = (uint8_t) (reg >> 8);
    buf[3] = (uint8_t) (reg & 0xFFU);
    buf[4] = (uint8_t) (value >> 8);
    buf[5] = (uint8_t) (value & 0xFFU);

    uint16_t crc = pzem_crc16(buf, 6U);
    buf[6] = (uint8_t) (crc & 0xFFU);
    buf[7] = (uint8_t) (crc >> 8);
    return 8U;
}

 

/* Verify the trailing CRC of a response frame. */
static bool pzem_check_crc(const uint8_t * frame, uint16_t len)
{
    if (len < 4U)
    {
        return false;
    }

    uint16_t calc = pzem_crc16(frame, (size_t) (len - 2U));
    uint16_t rx   = (uint16_t) frame[len - 2U] |
                    ((uint16_t) frame[len - 1U] << 8);
    return calc == rx;
}

 

/* Parse the 25-byte response from a measurement read. */
static bool pzem_parse_meas(const uint8_t * r, uint16_t len, pzem_data_t * out)
{

    if (len != PZEM_RESP_MEAS_LEN)              return false;
    if (r[1] != PZEM_FC_READ_INPUT)              return false;
    if (r[2] != (uint8_t) (PZEM_REG_MEAS_COUNT * 2U)) return false;
    if (!pzem_check_crc(r, len))                 return false;
    const uint8_t * d = &r[3];
    /* 16-bit registers are big-endian on the wire.                          *
     * 32-bit values use [low16, high16] register order (low reg comes 1st). */
    uint16_t v_raw = ((uint16_t) d[0] << 8) | d[1];
    uint32_t i_raw = ((uint32_t) d[2]  << 8)  |  (uint32_t) d[3]
                   | ((uint32_t) d[4]  << 24) | ((uint32_t) d[5] << 16);
    uint32_t p_raw = ((uint32_t) d[6]  << 8)  |  (uint32_t) d[7]
                   | ((uint32_t) d[8]  << 24) | ((uint32_t) d[9] << 16);
    uint32_t e_raw = ((uint32_t) d[10] << 8)  |  (uint32_t) d[11]
                   | ((uint32_t) d[12] << 24) | ((uint32_t) d[13] << 16);
    uint16_t f_raw  = ((uint16_t) d[14] << 8) | d[15];
    uint16_t pf_raw = ((uint16_t) d[16] << 8) | d[17];
    uint16_t al_raw = ((uint16_t) d[18] << 8) | d[19];
    out->voltage_v    = (float) v_raw  * 0.1f;
    out->current_a    = (float) i_raw  * 0.001f;
    out->power_w      = (float) p_raw  * 0.1f;
    out->energy_wh    = e_raw;
    out->frequency_hz = (float) f_raw  * 0.1f;
    out->power_factor = (float) pf_raw * 0.01f;
    out->alarm        = (al_raw == 0xFFFFU);
    return true;
}

/* =========================================================================
 * Generic single transaction (write request, wait for response).
 * Caller holds g_bus_mutex.
 * ========================================================================= */
static uint16_t pzem_xfer(const uint8_t * req, uint16_t req_len,
                          uint32_t first_byte_ms)
{
    pzem_rx_reset();
    if (!pzem_uart_send(req, req_len))
    {
        return 0U;
    }
    return pzem_uart_recv_frame(first_byte_ms, PZEM_INTER_BYTE_MS);
}

 

/* =========================================================================
 * Public single-shot helpers.
 * ========================================================================= */
static bool pzem_read_measurement(uint8_t addr, pzem_data_t * out)

{
    if (!g_uart_open) return false;
    uint8_t req[PZEM_REQ_READ_LEN];
    (void) pzem_build_read_req(req, addr, PZEM_FC_READ_INPUT,
                               PZEM_REG_MEAS_BASE, PZEM_REG_MEAS_COUNT);
    if (pdTRUE != xSemaphoreTake(g_bus_mutex, pdMS_TO_TICKS(100)))
    {
        return false;
    }
    uint16_t got = pzem_xfer(req, PZEM_REQ_READ_LEN, PZEM_FIRST_BYTE_MS);
    bool     ok  = false;
    if ((got >= 5U) && (g_rx_buf[0] == addr) &&
        (0U == (g_rx_buf[1] & PZEM_ERR_MASK)))
    {
        ok = pzem_parse_meas((const uint8_t *) g_rx_buf, got, out);
    }
    xSemaphoreGive(g_bus_mutex);
    vTaskDelay(pdMS_TO_TICKS(PZEM_INTER_FRAME_MS));
    return ok;
}

bool PZEM_ResetEnergy(uint8_t addr)
{
    if (!g_uart_open) return false;
    uint8_t  req[PZEM_REQ_RESET_LEN];
    req[0] = addr;
    req[1] = PZEM_FC_RESET_ENERGY;
    uint16_t crc = pzem_crc16(req, 2U);
    req[2] = (uint8_t) (crc & 0xFFU);
    req[3] = (uint8_t) (crc >> 8);
    if (pdTRUE != xSemaphoreTake(g_bus_mutex, pdMS_TO_TICKS(500)))
    {
        return false;
    }

    uint16_t got = pzem_xfer(req, PZEM_REQ_RESET_LEN, PZEM_FIRST_BYTE_MS);
    bool     ok  = false;

    if ((got >= 4U) && (g_rx_buf[0] == addr) &&
        (0U == (g_rx_buf[1] & PZEM_ERR_MASK)) &&
        pzem_check_crc((const uint8_t *) g_rx_buf, got))
    {
        ok = (g_rx_buf[1] == PZEM_FC_RESET_ENERGY);
    }
    xSemaphoreGive(g_bus_mutex);
    vTaskDelay(pdMS_TO_TICKS(PZEM_INTER_FRAME_MS));
    return ok;
}

bool PZEM_SetAlarmThreshold(uint8_t addr, uint16_t watts)
{
    if (!g_uart_open) return false;
    uint8_t req[PZEM_REQ_WRITE_LEN];
    (void) pzem_build_write_req(req, addr, PZEM_REG_ALARM_THR, watts);
    if (pdTRUE != xSemaphoreTake(g_bus_mutex, pdMS_TO_TICKS(500)))
    {
        return false;
    }
    uint16_t got = pzem_xfer(req, PZEM_REQ_WRITE_LEN, PZEM_FIRST_BYTE_MS);
    bool     ok  = false;
    /* Correct echo response: identical to request (incl. CRC). */
    if ((got == PZEM_REQ_WRITE_LEN) &&
        (0 == memcmp((const void *) g_rx_buf, req, PZEM_REQ_WRITE_LEN)))
    {
        ok = true;
    }

    xSemaphoreGive(g_bus_mutex);
    vTaskDelay(pdMS_TO_TICKS(PZEM_INTER_FRAME_MS));
    return ok;
}

 

bool PZEM_SetAddress(uint8_t current_addr, uint8_t new_addr)
{
    /* Valid slave addresses are 0x01..0xF7. */
    if ((new_addr < 0x01U) || (new_addr > 0xF7U))
    {
        return false;
    }
    if (!g_uart_open) return false;
    uint8_t req[PZEM_REQ_WRITE_LEN];
    (void) pzem_build_write_req(req, current_addr,
                                PZEM_REG_ADDRESS, (uint16_t) new_addr);
    if (pdTRUE != xSemaphoreTake(g_bus_mutex, pdMS_TO_TICKS(500)))
    {
        return false;
    }
    uint16_t got = pzem_xfer(req, PZEM_REQ_WRITE_LEN, PZEM_FIRST_BYTE_MS);
    bool     ok  = (got == PZEM_REQ_WRITE_LEN) &&
                   (0 == memcmp((const void *) g_rx_buf, req, PZEM_REQ_WRITE_LEN));
    xSemaphoreGive(g_bus_mutex);
    vTaskDelay(pdMS_TO_TICKS(PZEM_INTER_FRAME_MS));
    return ok;
}

 

bool PZEM_GetData(pzem_data_t * out)
{
    if ((NULL == out) || (NULL == g_data_q))
    {
        return false;
    }
    return pdTRUE == xQueuePeek(g_data_q, out, 0);
}

uint32_t PZEM_GetLastSampleMs(void){
    return g_last_sample_ms;
}
/* =========================================================================
 * Task entry.
 * ========================================================================= */
void PZEM_entry(void * pvParameters)
{
    FSP_PARAMETER_NOT_USED(pvParameters);
    /* RTOS objects. */
    g_bus_mutex = xSemaphoreCreateMutexStatic(&g_bus_mutex_buf);
    g_tx_sem    = xSemaphoreCreateBinaryStatic(&g_tx_sem_buf);
    g_rx_sem    = xSemaphoreCreateBinaryStatic(&g_rx_sem_buf);
    g_data_q    = xQueueCreateStatic(1U,
                                     sizeof(pzem_data_t),
                                     g_data_q_storage,
                                     &g_data_q_buf);
    /* Open the SCI UART. */
    if (FSP_SUCCESS != R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg))
    {
        vTaskDelete(NULL);
        return;
    }
    /* Force 9600 baud regardless of what the configurator chose, so this
     * driver works with whatever default the project has. */
    baud_setting_t baud_cfg;
    if (FSP_SUCCESS == R_SCI_UART_BaudCalculate(PZEM_BAUDRATE,
                                                false,
                                                5000U,
                                                &baud_cfg))
    {
        (void) R_SCI_UART_BaudSet(&g_uart0_ctrl, &baud_cfg);
    }
    /* Hook our callback (configurator left it as NULL). */
    (void) R_SCI_UART_CallbackSet(&g_uart0_ctrl, pzem_uart_cb, NULL, NULL);
    g_uart_open = true;
    /* Give the meter a moment to be ready after power-up. */
    vTaskDelay(pdMS_TO_TICKS(100));
    pzem_data_t sample;
    TickType_t  last_wake = xTaskGetTickCount();
    while (1)
    {
        if (pzem_read_measurement(PZEM_ADDR_GENERAL, &sample))
        {
            (void) xQueueOverwrite(g_data_q, &sample);
            g_last_sample_ms = (uint32_t)(xTaskGetTickCount() * portTICK_PERIOD_MS);
        }
        vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(PZEM_POLL_PERIOD_MS));
    }
}
